ALTER TABLE employe ALTER COLUMN actif DROP DEFAULT;
ALTER TABLE employe ALTER COLUMN actif TYPE BOOLEAN USING CASE WHEN actif::text IN ('1', 't', 'true') THEN TRUE ELSE FALSE END;
ALTER TABLE employe ALTER COLUMN actif SET DEFAULT TRUE;